# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160217_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptprofile',
            name='_summary_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptprofile',
            name='summary',
            field=markupfield.fields.MarkupField(default='', rendered_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptprofile',
            name='summary_markup_type',
            field=models.CharField(choices=[(b'', b'--'), (b'markdown', b'markdown')], default='markdown', editable=False, max_length=30),
        ),
    ]
