# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160315_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='remote',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
