# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
        ('blog', '0009_auto_20160315_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=1000)),
                ('source_location', models.URLField(blank=True, max_length=500, null=True)),
                ('identifier', models.CharField(max_length=1000)),
                ('identifier_type', models.CharField(max_length=1000)),
                ('description', markupfield.fields.MarkupField(rendered_field=True)),
                ('resource_type', models.CharField(choices=[('WB', 'Website'), ('JO', 'Journal article'), ('BK', 'Book'), ('PE', 'Periodical article'), ('DT', 'Dataset')], max_length=2)),
                ('description_markup_type', models.CharField(choices=[(b'', b'--'), (b'markdown', b'markdown')], default='markdown', editable=False, max_length=30)),
                ('created_original', models.DateField()),
                ('_description_rendered', models.TextField(editable=False)),
                ('about', models.ManyToManyField(blank=True, to='concepts.Concept')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
