# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160315_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdfclass',
            name='subClassOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superClassOf', to='blog.RDFClass'),
        ),
        migrations.AlterField(
            model_name='rdfproperty',
            name='subPropertyOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superPropertyOf', to='blog.RDFProperty'),
        ),
    ]
