# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160317_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('blog.entity',),
        ),
        migrations.AlterField(
            model_name='genecologyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address'),
        ),
    ]
