# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160920_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_source', models.CharField(choices=[('EN', 'Evernote')], max_length=2)),
                ('retrieved', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('local_note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_note', to='blog.Note')),
            ],
        ),
    ]
