# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_externalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalNotebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_source', models.CharField(choices=[('EN', 'Evernote')], max_length=2)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_notebooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='externalnote',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalnote',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.ExternalNotebook'),
        ),
    ]
