# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
        ('blog', '0020_externalembeddedresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('name', models.CharField(help_text='If available, use the original title of the resource. Otherwise, create a concise but descriptive title (e.g. "James Gregor obituary").', max_length=255)),
                ('source', models.CharField(help_text='Name of the source (e.g. name of a newspaper, website).', max_length=1000)),
                ('source_location', models.URLField(blank=True, help_text='For online resources, this should be the location of the resource. For archives, this should be a link to the finding aid, if available.', max_length=500, null=True)),
                ('identifier', models.CharField(help_text='The unique identifier used to refer to the original resource. For archives, this could be a collection/bundle/item identifier. For web resources, this coud be the URL (i.e. same as source location).', max_length=1000)),
                ('identifier_type', models.CharField(choices=[('url', 'URL'), ('uri', 'URI'), ('archive', 'Archival identifier'), ('catalog', 'Library catalog identifier'), ('doi', 'DOI'), ('handle', 'Handle'), ('isbn', 'ISBN'), ('issn', 'ISSN'), ('other', 'Other')], max_length=1000)),
                ('description', markupfield.fields.MarkupField(help_text='Depends on the resource type. To quote the original resource, use the markdown blockquote, e.g. "&gt; Here is some quoted text".', rendered_field=True)),
                ('description_markup_type', models.CharField(choices=[(b'', b'--'), (b'markdown', b'markdown')], default='markdown', editable=False, max_length=30)),
                ('_description_rendered', models.TextField(editable=False)),
                ('file_obj', models.FileField(blank=True, null=True, upload_to='generic/')),
                ('remote', models.URLField(blank=True, max_length=500, null=True)),
                ('about', models.ManyToManyField(blank=True, to='concepts.Concept')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instance_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.RDFClass')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
