# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_genericresource_original_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('external_source', models.CharField(choices=[('EN', 'Evernote')], max_length=2)),
                ('label', models.CharField(max_length=255)),
                ('local_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tags', to='blog.Tag')),
            ],
        ),
    ]
