# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_externaltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresource',
            name='created_original',
            field=models.DateField(blank=True, help_text='Date on which the original resource was created. For example, the publication date of an article.', null=True, verbose_name='original creation date'),
        ),
    ]
