# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20160923_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
